#include <stdio.h>

// 请根据主程序流程，补全此函数
// 冰雹产生并输出函数
// 注意：输出每个冰雹数时，请按5位对齐输出
void hailstone(int n)
{
    printf("Hailstone generated by %d:\n", n);
    /**********  Begin **********/
    int count = 0;
    for (int i = 1; 1; i++)
    {
        count = i;
        printf("%5d", n);
        // getchar();
        if (!(i % 6))
        {
            printf("\n");
        }

        if (n == 1)
        {
            break;
        }
        else if (n % 2)
        {
            n = n * 3 + 1;
        }
        else
        {
            n /= 2;
        }
    }

    /**********  End  **********/
    // printf("%5d\n",n);
    printf("\nNumber of hailstone generated:%d", count);
}

// 请根据此函数补全文件step2_stu.h中冰雹产生函数
int main()
{
    int number;

    printf("input a number:");
    scanf("%d", &number);

    hailstone(number);

    return 0;
}